version: "3"

includes:
  install: ./Taskfile.install.yml

tasks:
  create-python-virtual-environment:
    cmds: 
      - python -m venv venv
  
  freeze-requirements:
    cmds: 
      - pip3 freeze > requirements.txt