apiVersion: batch/v1
kind: Job
metadata:
  name: "db-migrations"
  labels:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "db-migrations"
    spec:
      restartPolicy: Never
      containers:
        - name: "db-migrations"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
